server:
  port: 8080

spring:
  application:
    name: openapi-example
  
  # OpenAPI 설정
  doc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html
      operations-sorter: method
      tags-sorter: alpha

  # 개발 도구 설정
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

# 로깅 설정
logging:
  level:
    com.example.openapi: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n" 