server:
  port: 8080

spring:
  application:
    name: openapi-example
  
  # MariaDB 설정
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/netis
    username: netis
    password: ntflow
  
  # OpenAPI 설정
  doc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html
      operations-sorter: method
      tags-sorter: alpha

  # 개발 도구 설정
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

# MyBatis 설정
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.openapi.dto
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 로깅 설정
logging:
  level:
    com.example.openapi: DEBUG
    org.springframework.web: DEBUG
    com.example.openapi.mapper: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n" 